name: E2E
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'End-to-end Tests'
  # Cron job to run e2e tests @ 8:30 pm daily on the latest commit on the default branch - main
  schedule:
    - cron: '30 20 * * *'

# Cancel any in progress run of the workflow for a given PR
# This avoids building outdated code
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  android:
    env:
      working-directory: ./packages/mobile
    name: Android
    runs-on: android-e2e-group
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Install package dependencies
        run: yarn
      - name: Fail if someone forgot to commit "yarn.lock"
        run: git diff --exit-code
      - name: Build mobile dependencies
        run: yarn build --scope @celo/mobile --include-filtered-dependencies
      - name: Make jest available
        working-directory: ${{env.working-directory}}
        run: cp ../../node_modules/.bin/jest node_modules/.bin/
      - name: Create Detox Build
        working-directory: ${{env.working-directory}}
        run: |
          export CELO_TEST_CONFIG=e2e
          export ANDROID_SDK_ROOT=$HOME/android-tools
          yarn detox build -c android.release
      - name: Run Detox
        working-directory: ${{env.working-directory}}
        run: >
          export CELO_TEST_CONFIG=e2e &&
          export ANDROID_SDK_ROOT=$HOME/android-tools &&
          yarn detox test
          --configuration android.release
          --artifacts-location e2e/artifacts
          --take-screenshots=failing
          --record-videos=failing
          --record-logs=failing
          --loglevel info
          --debug-synchronization 10000
          --workers 3
          --headless
          --device-boot-args="-snapshot ci_boot"
        timeout-minutes: 45
      - name: Publish Android JUnit Report
        if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: Android e2e Test Report
          report_paths: 'packages/mobile/e2e/test-results/junit.xml'
      - name: 'Upload Android E2E Artifacts'
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: android-e2e-artifact
          path: packages/mobile/e2e/artifacts
      - name: 'Upload Android E2E HTML Report'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: android-e2e-test-report
          path: packages/mobile/e2e/test-results
